version: "2.1"
services:

  application:
    container_name: application
    build:
      context: .
    depends_on:
      - postgres
      - keycloak
    ports:
      - "8080:8080"

  postgres:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/.:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/.:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
volumes:
  postgres-data:
    driver: local
  keycloak-data:
    driver: local
