version: "2.1"
services:

  application:
    container_name: application
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "3000:3000"

  postgres:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
volumes:
  postgres-data:
