version: "2.1"
services:

  application:
    container_name: application
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "3000:3000"

  postgres:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"