global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['prometheus:9090']
          labels:
            app: 'Prometheus'
    - job_name: 'cluster-api'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['application:8080']
          labels:
            app: 'TicketManagementSystem'
      oauth2:
        client_id: 'TicketManagementSystem'
        client_secret: "eoM7Xo7Ft93eyph81RnfSiNcJ9Cawvfw"
        token_url: 'http://keycloak:8080/realms/ticket_management_system/protocol/openid-connect/token'
        endpoint_params:
          grant_type: "password"
          username: "prometheus"
          password: "password"
