global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['prometheus:9090']
          labels:
            app: 'Prometheus'
    - job_name: 'cluster-api'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['application:8080']
          labels:
            app: 'TicketManagementSystem'
