name: Build and Push Application Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag v1.0.0 or v1.3.2-alpha for non production'
        required: true

jobs:

  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push application
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: matteorosani/ticket-management-system:${{ github.event.inputs.tag_name || github.event.release.tag_name }}
